### ISSUE TITLE
Is it possible to use resize proxies/filters in CSS?

### ISSUE THREAD

**Issue by alekseyg** [jekyll/jekyll-assets#177]
The documentation is silent on the subject. If it's possible, it should be documented. If it's not, it may be worth adding. Is it possible to use image resizing/cropping/etc. in CSS like in Liquid? As for version, is it possible in any version, 1.0.0, or master, aka Jekyll-Assets 3? I've tried the following with 1.0.0, but with no luck.

``` CSS
.home { background-image: url(asset_path(pages/home.jpg [resize:1280x720])); }
```
