### ISSUE TITLE
Non digest (dev mode) breaks sprockets-sass

### ISSUE THREAD

**Issue by swernerx** [jekyll/jekyll-assets#193]
While upgrading to Jekyll-3 I found another issue. When not setting the "digest" property in the config file the sass integration with sprockets-sass does not seem to work (in development mode). Sass/Sprockets seems to use the hashed/digested file names, while Jekyll-assets does not use them.

Is this related to the Sass integration or the Jekyll-asset changes?

**Comment by envygeeks** [comment]
You are being too broad, I have no idea what you are doing or how you are doing it, provide more information so we can cover the surface if it's appropriate, we provide helpers which clearly do what we tell them to do: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/hooks/helpers.rb if you do not use our helpers that is not a surface I am willing to cover.

**Comment by envygeeks** [comment]
What is "sprockets-sass"? We do not support that and do not plan to and if it's this: https://github.com/petebrowne/sprockets-sass we have no plans to ever support that, we provide our own helpers, we do not support ERB (and never will,) and we already provide compass support.

**Comment by swernerx** [comment]
Yep, it's exactly this. Okay, I am definitely happy if there is a new way to implement these things through. I am just saying that this worked before using this module. What I was using was this:

```scss
@font-face {
  font-family: "SSoft Glober Hinted";
  font-weight: 100;
  font-style: normal;

  src: font-url("web/Glober-Thin-subset-hinted.woff2") format("woff2"),
       font-url("web/Glober-Thin-subset-hinted.woff") format("woff"),
       font-url("web/Glober-Thin-subset-hinted.ttf") format("truetype");
}
```

This worked for registering assets so that they were copied to the "site" folder + also let me use the digesting methods so that I have hashed file names.

Is there an alternative solution for doing this? Hopefully without using Compass which we currently did not used at all.

**Comment by envygeeks** [comment]
We should probably document the helpers, I'll make sure to do that before release, but we do provide helpers like that but they are `_` and it's "path" so it would change to:

```scss
@font-face {
  font-family: "SSoft Glober Hinted";
  font-style: normal;
  font-weight: 100;

  src: font_path("web/Glober-Thin-subset-hinted.woff2") format("woff2"),
       font_path("web/Glober-Thin-subset-hinted.woff")  format("woff"),
       font-path("web/Glober-Thin-subset-hinted.ttf")   format("truetype");
}
```

The helpers are:

* `asset_path`
* `image_path`
* `font_path`

And because our path helpers do not tap the file system we also add http and digests as necessary for you, along with prefixes and base-urls.
