### ISSUE TITLE
Migration tutorial or example app?

### ISSUE THREAD

**Issue by kvz** [jekyll/jekyll-assets#229]
Hi, I'm trying to upgrade from 1.0 to 2.1 and am finding some big changes. I'm not quite sure what all of them are though. I'm comparing the old readme to the new, and doing a lot of trial & error, but so far I have not been able to get Less building to work for instance.

Is there an example app or migration tutorial / blog post that could provide some more insight?

I'm quite low on Ruby-fu so convinced I'm doing something silly, but I could use some pointers to figure out what.

For what it's worth, these are relevant snippets of the involved files:

`Gemfile`:

```Gemfile
source 'https://rubygems.org'
gem 'addressable', '2.4.0'
gem 'autoprefixer-rails', '6.2.3'
gem 'blankslate', '3.1.3'
gem 'hike', '2.1.3'
gem 'html-pipeline', '2.2.2'
gem 'jekyll-assets', '2.1.0'
gem 'jekyll-feed', '0.4.0'
gem 'jekyll-redirect-from', '0.9.1'
gem 'jekyll-sitemap', '0.9.0'
gem 'jekyll', '3.0.1'
gem 'jemoji', '0.5.1'
gem 'libv8', '3.16.14.13'
gem 'liquid', '3.0.6'
gem 'parslet', '1.7.1'
gem 'sprockets-es6', '0.8.2'
gem 'sprockets', '3.5.2'
gem 'tilt', '2.0.1'
gem 'jekyll-seo-tag', '0.1.3'
```

`_config.yml`:

```yaml
gems:
  - jemoji
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-redirect-from

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/bower
  autoprefixer:
    browsers: ["> 1%","last 4 versions","IE > 8"]

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
```

`_assets/javascripts/app.js`:

```javascript
// many more requires 
// Jsonform
//=require jsonform/lib/jsonform
//=require common
```

`_assets/stylesheets/app.css`:

```less
@import (less) "bootstrap/less/bootstrap.less";
```

`_layouts/default.html`:

```html
<head>
 {% stylesheet app %}
</head>
<body>
...
</body>
{% javascript app %}
```

And I'm running into the problem where an error  `Liquid Exception: Liquid syntax error: Tag '{%' was not properly terminated with regexp: /\%\}/ in _layouts/default.html` is thrown. This goes away when I remove the `{% javascript app %}` from `default.html`, but then of course I lose my JavaScript build..

I also tried to name my assets file `app.css.less` as well as `app.less`, to signal that there's Less in the file, and not straight up CSS. But when I try those, I run into:

`Liquid Exception: Could not find the asset 'app' in _layouts/default.html`.

Sorry if this goes all over the place, but after a day of tinkering it would be great if someone could show me the way.
