### ISSUE TITLE
Javascript compress?

### ISSUE THREAD

**Issue by ikus060** [jekyll/jekyll-assets#233]
Hello,

Reading the README jekyll-assets should compress my javascript. But it doesn't seams to work. I probably miss something either a gem or a config...

_config.yml:
```
[...]
# Assets settings.
gems:
- jekyll-assets
- mini_magick
assets:
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: false
  sources:
    - /assets
  features:
    liquid: false
    automatic_img_size: false
    automatic_img_alt : false
[...]
```
_includes/_head.html:
```
[...]
{% javascript js/main %}
[...]
```
_assets/js/main.js:
```
//= require js/vendor/jquery.min
//= require js/vendor/bootstrap.min
//= require js/plugins/bootstrap-formhelpers
//= require js/plugins/ekko-lightbox
//= require js/plugins/jquery.validate
```
