### ISSUE TITLE
keep folders named for proxied assets

### ISSUE THREAD

**Issue by ikus060** [jekyll/jekyll-assets#234]
Hello using jekyll-assets with the following configuration, I'M expecting proxied assets to be generated aside the original file.
_config.yml:
```
assets:
  prefix: "/assets"
  sources:
    - assets
```
Using `{% image "posts/markdown.png" magick:resize:212x150^ %}` will generate a files `_site/assets/markdown-757a1b9d2cf8395d2a7b379107b9a9cc388987a5306643e0e95ffb23320929cb.png` while I'm expecting a file to be generated at `_site/assets/posts/...`.

Ref #209
