### ISSUE TITLE
Usage of tags in the front-matter.

### ISSUE THREAD

**Issue by arron-jeffery** [jekyll/jekyll-assets#238]
Hey!

Forgive me if there's a obvious way to achieve this but I couldn’t find much information about it after browsing the documentation. I’ve been wondering if it’s possible to reference an asset within the front-matter. For example:

```
---
title: ''
layout: ''
cover_photo:
  src: '{% asset_path "posts/sample-post/cover.jpg" %}'
  color: #fafafa
---
```

If this isn't currently possible, will there be plans to support this in the future?

Many Thanks!
