### ISSUE TITLE
I can't seem to get Jekyll Assets to work

### ISSUE THREAD

**Issue by mikidep** [jekyll/jekyll-assets#240]
I followed the instructions in the README (except that I installed it via `gem install` rather than using the Gemfile), I added this to my _config.yml:
```
gems:
  - jekyll-assets

assets:
    prefix: "/assets"
    sources:
        - _assets/js
```
And this is my _assets folder:
![image](https://cloud.githubusercontent.com/assets/725536/12744711/001950ea-c996-11e5-9d51-805ac9e23b31.png)
I restarted the server and all, still, no trace of the JS files in the generated site. What am I missing?
