### ISSUE TITLE
I don't understand how to use jekyll-assets to combine js-files to one

### ISSUE THREAD

**Issue by paulgeisler** [jekyll/jekyll-assets#241]
I apologise in advance because i've just started using jekyll and my understanding of ruby and sprockets is very limited.

Maybe it's the wrong approach and usage of jekyll-assets...
My intend is to combine some (3/28) of the foundation js-files to one main.js file and place it in `_site/assets/js` folder.
I don't want jekyll-assets to copy all foundation js-files over to _site/assets/foundation folder.

My folder structure is:
`app/_assets/javascript/foundation/(foundation-js-plugins)`
`app/_assets/javascript/main.js`

My `main.js` is:
````
//=require foundation/foundation.core
//=require foundation/foundation.tabs
//=require foundation/foundation.reveal
````
My `_config.yml`` is:
`````
gems:
- jekyll-assets

assets:
    sources:
        - _assets/
    compress:
        css: false

sass:
    style: nested
    line_numbers: true
    sourcemap: file
````

I understand that jekyll-assets is designed to take the whole _assets folder, process it (minifying, uglifing and so on) and place it in the _site folder. But maybe there is a way to solve my problem.

My background is PHP and Grunt. Perhaps i'm looking from a different/wrong angle at jekyll and jekyll-assets and there is a better/right approach to use and combine only needed js-files but have a lot of them... somewhere.
With Grunt i can have an assets-folder, explicitly combine the files i need to one and place only this one file in the (for example) build-folder.
