### ISSUE TITLE
Refreshing a page before it's finished building breaks the build

### ISSUE THREAD

**Issue by admhlt** [jekyll/jekyll-assets#284]
We use jekyll-assets a _lot_, and have been getting an error very frequently that's disrupting our workflow. Often, it seems like if we try to refresh changes to a page, the browser attempts to render the page before the CSS and JS assets are built, resulting in an unstyled page:

![unrendered-page](https://cloud.githubusercontent.com/assets/6955296/15438134/aea77e82-1e98-11e6-9589-cc2b4acc8414.png)

This is accompanied by "asset not found" errors in our terminals:

![terminal-assets-not-found](https://cloud.githubusercontent.com/assets/6955296/15438143/b95b1dde-1e98-11e6-99b4-65087f7ea498.png)

Is there some way to avoid this? Is there a caching flag we should have turned on so that assets have to be compiled less frequently?

This is our entire jekyll-assets config:

``` yaml
assets:
  prefix: "/assets"
  sources:
    - assets/images
    - assets/javascripts
    - assets/stylesheets
```
