### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll-assets#302]
I keep looking at the website, the readmes, and the wiki, I'm having a hard time exactly understand what this project does, and how to get started.

It could do with some introductions about the basic idea before going into configuration reference.

My example is this so far:
- I have an existing Jekyll site running, with javascript files in a `/js` directory.
- I am looking to compress my javascript sources (following Google sitespeed recommendations).
- I added the following to my config.yml:

```
assets:
  digest: true
  compress:
    js: true
  assets:
    - "*.js"
  sources:
    - js
```

I have no idea what the expected result should be. My javascript files don't look compressed, no errors, everything is the same ...
