### ISSUE TITLE
Undefined method `jekyll' for #<Sprockets::CachedEnvironment:0x007feaa0992130>

### ISSUE THREAD

**Issue by mebibou** [jekyll/jekyll-assets#303]
Just installed Jekyll into my rails app, and wanted to use `jekyll-assets` for handling the assets from the Rails project.
Jekyll is installed under the `/news` directory of the Rails app. My `jekyll.conf` file is:
```yaml
plugins:
  - jekyll-assets

# assets
assets:
  dirname: assets
    baseurl: /news/assets/
    sources:
      - _assets/stylesheets
      - _assets/javascripts
      - _assets/images
    js_compressor: uglifier
    css_compressor: sass
```

Now when I try to access `http://localhost:3000/` (which I do not want to be handled by Jekyll), I get the following error:
```sh
NoMethodError - undefined method `jekyll' for #<Sprockets::CachedEnvironment:0x007feaa0992130>:
  jekyll-assets (2.2.7) lib/jekyll/assets/processors/liquid.rb:12:in `call'
  sprockets (3.6.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
  ...
```
