### ISSUE TITLE
asset_path, asset_url font_path is not honoring the site.baseurl in sass files

### ISSUE THREAD

**Issue by RishikeshDarandale** [jekyll/jekyll-assets#320]
I am trying to use asset_path in my sass file as below:

```
background: url(asset_url('home/home.jpg'));
```

But, looks like baseurl is not honored and url is getting generated as 

```
background-image:url(url(/assets/home/home-ff8cf2b518175392978a4426a77a19472c7645c7daaf17fbce2d08130d771112.jpg));
```

Here is the configuration for jekyll-assets

```
assets:
  prefix: "/assets"
  digest: true
  sources:
    - _assets/fonts
    - _assets/imgages
    - _assets/javascripts
    - _assets/stylesheets
  compress:
    css: sass
    js: uglifier
  features:
    automatic_img_alt: true
    automatic_img_size: false
```
