### ISSUE TITLE
Question: how do I wrap the JS bundle in an IIFE?

### ISSUE THREAD

**Issue by timmywil** [jekyll/jekyll-assets#370]
Everything is concatenated together fine, but I'm trying to wrap the final bundle in an IIFE so all my variables aren't global. I've tried adding the enclose option:

```
assets:
  compress:
    js: true
    css: true
  external:
    uglifier:
      enclose: {}
```

But this doesn't seem to be working. Any suggestions?

Example:

main.js
```js
//= require utils
console.log('utils usable: ', utils)
```

utils.js
```js
var utils = {
  method: function () {}
}
```

Note you can't just add a closure to main.js.
