### ISSUE TITLE
Preserve comments with Uglifier

### ISSUE THREAD

**Issue by hackedunit** [jekyll/jekyll-assets#387]
The suggested way to preserve comments with Uglifier is to pass options like this in _config.yml

```
assets:
  external:
    uglifier:
      output:
        comments: /^!/
```

but when Jekyll loads config values, it converts them to string, including the regular expression and hence these config values are passed to uglifier as `:output => {:comments => "/^!/"}` (note the double quotes around the regex) which fails to be detected as a valid regexp.

How can we load reg expressions properly from config without converting to string?
