### ISSUE TITLE
Liquid Exception: SyntaxError: Unexpected token: name (Util) in /_layouts/default.html

### ISSUE THREAD

**Issue by cmoulliard** [jekyll/jekyll-assets#392]
When the following layout page 

```
<!DOCTYPE html>
<html lang="{{ page.lang | default: site.lang | default: 'en' }}">
{% include head.html %}
<body>
<div class="container">
    {% include nav-bar.html %}
    <div class="container">
        {{ content }}
    </div>
    <footer class="footer">
        <p>&copy; Red Hat 2017</p>
    </footer>
</div>
{% js main %}
</body>
</html>
```

is processed using this command `JEKYLL_ENV=production bundle exec jekyll build` with jekyll 3.5.0, then I get this liquid error 

```
Configuration file: /Users/dabou/Code/snowdrop/site/_config.yml
            Source: /Users/dabou/Code/snowdrop/site
       Destination: /Users/dabou/Code/snowdrop/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    SyntaxError: Unexpected token: name (Util)
  Liquid Exception: SyntaxError: Unexpected token: name (Util) in /_layouts/default.html
```

Here is the config used

```
sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: false
    js: true
  sources:
    - _assets/js

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-assets
```
