### ISSUE TITLE
Build Warning: Layout requested does not exist

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll-assets#407]
I am adding Jekyll Assets to my site and get the following error on build. I have changed the `link` tag for the main CSS file to `{% css style %}` as this is the name of the compiled and compressed file. My styles are located in `_assets`. Is this looking at the correct file?

I have the following assets configuration: 

```
assets:
  compress:
    css: default
    js: default
  autowrite: true
  cache: default
  cache_type: default
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  sources:
    - _assets/css
  features:
    liquid: default
    integrity: default
    # This will add height and width attributes for an img tag.
    automatic_img_size: default
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : default
```
